AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Instancetype:
    Description: EC2 Instance Type
    Type: String
    Default: t2.micro
    AllowedValues:
     - t2.micro
     - t2.small
     - m4.large

  
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref Instancetype
      ImageId: ami-090fa75af13c156b4
      SecurityGroups:
       - !Ref InstanceSecurityGroup
      KeyName: sreekanth1
                

      Tags:
        - Key: Name
          Value: github
          
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:  
      GroupDescription: Enable SSH accees via port 22
      SecurityGroupIngress:
       - IpProtocol: tcp
         FromPort: 22
         ToPort: 22
         CidrIp: 0.0.0.0/0
       - IpProtocol: tcp
         FromPort: 80
         ToPort: 80
         CidrIp: 0.0.0.0/0
       - IpProtocol: tcp
         FromPort: 443
         ToPort: 443
         CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: EC2-SG          
Outputs:
  InstanceId:
    Description: instanceId of the EC@ instance
    Value: !Ref EC2Instance
